services:
  mysql:
    image: mysql:8
    env:
      MYSQL_DATABASE: dangbun
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    options: >-
      --health-cmd="mysqladmin ping -h localhost"
      --health-interval=10s
      --health-timeout=5s
      --health-retries=3
