services:
  mysql:
    image: mysql:8
    env:
      MYSQL_DATABASE: dangbun
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - 3306:3306
    options: >-
      --health-cmd="mysqladmin ping -h mysql -u root -proot"
      --health-interval=10s
      --health-timeout=5s
      --health-retries=5

env:
  SPRING_PROFILES_ACTIVE: local
  LOCAL_DB_USER: testuser
  LOCAL_DB_PASSWORD: testpass
  LOCAL_DB_URL: jdbc:mysql://mysql:3306/dangbun
